Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: /crypto/ordererOrganizations/ficct.edu.bo/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &FICCTOrg
        Name: FICCTOrg
        ID: FICCTOrgMSP
        MSPDir: /crypto/peerOrganizations/ficct.edu.bo/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('FICCTOrgMSP.admin', 'FICCTOrgMSP.peer', 'FICCTOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('FICCTOrgMSP.admin', 'FICCTOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('FICCTOrgMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('FICCTOrgMSP.peer')"
        AnchorPeers:
            - Host: peer0.ficct.edu.bo
              Port: 7051

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_5: true

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
        - orderer.ficct.edu.bo:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    EtcdRaft:
        Consenters:
            - Host: orderer.ficct.edu.bo
              Port: 7050
              ClientTLSCert: /crypto/ordererOrganizations/ficct.edu.bo/orderers/orderer.ficct.edu.bo/tls/server.crt
              ServerTLSCert: /crypto/ordererOrganizations/ficct.edu.bo/orderers/orderer.ficct.edu.bo/tls/server.crt
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    EvotingOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities: *OrdererCapabilities
        Consortiums:
            EvotingConsortium:
                Organizations:
                    - *FICCTOrg

    EvotingChannel:
        Consortium: EvotingConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *FICCTOrg
            Capabilities: *ApplicationCapabilities
