import { Context, Contract, Info, Returns, Transaction } from 'fabric-contract-api';
import { ElectionState } from './models/election-state.model';
import { TallyAsset } from './models/tally.model';
import { VoteAsset } from './models/vote.model';

// ── State key helpers ─────────────────────────────────────────────────────────
const voteKey = (voteId: string) => `vote:${voteId}`;
const tallyKey = (electionId: string) => `tally:${electionId}`;
const electionKey = (electionId: string) => `election:${electionId}`;

@Info({ title: 'FicctVoting', description: 'FICCT e-voting smart contract' })
export class VotingContract extends Contract {
  constructor() {
    super('FicctVoting');
  }

  // ── initEleccion ────────────────────────────────────────────────────────────
  // Called by NestJS when election transitions PROGRAMADA → ACTIVA.
  // Creates the gate the chaincode checks before accepting votes.

  @Transaction()
  async initEleccion(ctx: Context, electionId: string): Promise<void> {
    const key = electionKey(electionId);
    const existing = await ctx.stub.getState(key);

    if (existing && existing.length > 0) {
      throw new Error(`La elección ${electionId} ya fue inicializada`);
    }

    const state: ElectionState = {
      assetType: 'electionState',
      electionId,
      status: 'ACTIVA',
      openedAt: new Date().toISOString(),
    };

    const tally: TallyAsset = {
      assetType: 'tally',
      electionId,
      results: { votos_blancos: 0, votos_nulos: 0 },
      lastUpdated: state.openedAt,
    };

    await ctx.stub.putState(key, Buffer.from(JSON.stringify(state)));
    await ctx.stub.putState(tallyKey(electionId), Buffer.from(JSON.stringify(tally)));
  }

  // ── emitirVoto ──────────────────────────────────────────────────────────────
  // voteId must be an anonymous UUID generated by NestJS (never contains RU).
  // Returns the Fabric txId so NestJS can give the voter a receipt.

  @Transaction()
  @Returns('string')
  async emitirVoto(
    ctx: Context,
    voteId: string,
    electionId: string,
    candidateId: string,
  ): Promise<string> {
    // 1. Verify election is open
    const elecBytes = await ctx.stub.getState(electionKey(electionId));
    if (!elecBytes || elecBytes.length === 0) {
      throw new Error(`Elección ${electionId} no encontrada en el ledger`);
    }
    const elecState: ElectionState = JSON.parse(elecBytes.toString());
    if (elecState.status !== 'ACTIVA') {
      throw new Error(`La elección ${electionId} no está activa (estado: ${elecState.status})`);
    }

    // 2. Prevent duplicate voteId
    const voteBytes = await ctx.stub.getState(voteKey(voteId));
    if (voteBytes && voteBytes.length > 0) {
      throw new Error(`voteId ${voteId} ya existe en el ledger — voto duplicado`);
    }

    const txId = ctx.stub.getTxID();
    const ts = ctx.stub.getTxTimestamp();
    const timestamp = new Date(
      (ts.seconds.toNumber() * 1000) + Math.floor(ts.nanos / 1e6),
    ).toISOString();

    // 3. Persist vote asset
    const vote: VoteAsset = {
      assetType: 'vote',
      id: voteId,
      electionId,
      candidateId,
      timestamp,
      txId,
    };
    await ctx.stub.putState(voteKey(voteId), Buffer.from(JSON.stringify(vote)));

    // 4. Update tally atomically in same transaction
    await this._incrementTally(ctx, electionId, candidateId, timestamp);

    return txId;
  }

  // ── getResultados ───────────────────────────────────────────────────────────
  // Returns the live TallyAsset directly from CouchDB world state.
  // Results are authoritative — never computed in NestJS.

  @Transaction(false)
  @Returns('string')
  async getResultados(ctx: Context, electionId: string): Promise<string> {
    const bytes = await ctx.stub.getState(tallyKey(electionId));
    if (!bytes || bytes.length === 0) {
      throw new Error(`No hay resultados para la elección ${electionId}`);
    }
    return bytes.toString();
  }

  // ── verificarVoto ───────────────────────────────────────────────────────────
  // Looks up a VoteAsset by txId using a CouchDB rich query.
  // Returns the asset without revealing voter identity (voteId is anonymous).

  @Transaction(false)
  @Returns('string')
  async verificarVoto(ctx: Context, txId: string): Promise<string> {
    const query = JSON.stringify({
      selector: { assetType: 'vote', txId },
      limit: 1,
    });

    for await (const kv of ctx.stub.getQueryResult(query)) {
      if (kv.value && kv.value.length > 0) {
        return Buffer.from(kv.value).toString('utf8');
      }
    }

    throw new Error(`Transacción ${txId} no encontrada en el ledger`);
  }

  // ── cerrarEleccion ──────────────────────────────────────────────────────────
  // Seals the election so no further votes are accepted.
  // Finalizes the tally snapshot with a closedAt timestamp.

  @Transaction()
  @Returns('string')
  async cerrarEleccion(ctx: Context, electionId: string): Promise<string> {
    const key = electionKey(electionId);
    const bytes = await ctx.stub.getState(key);

    if (!bytes || bytes.length === 0) {
      throw new Error(`Elección ${electionId} no encontrada en el ledger`);
    }

    const state: ElectionState = JSON.parse(bytes.toString());
    if (state.status === 'CERRADA') {
      throw new Error(`La elección ${electionId} ya está cerrada`);
    }

    const ts = ctx.stub.getTxTimestamp();
    const closedAt = new Date(
      (ts.seconds.toNumber() * 1000) + Math.floor(ts.nanos / 1e6),
    ).toISOString();

    state.status = 'CERRADA';
    state.closedAt = closedAt;

    await ctx.stub.putState(key, Buffer.from(JSON.stringify(state)));

    // Stamp the tally with the final close time
    const tallyBytes = await ctx.stub.getState(tallyKey(electionId));
    if (tallyBytes && tallyBytes.length > 0) {
      const tally: TallyAsset = JSON.parse(tallyBytes.toString());
      tally.lastUpdated = closedAt;
      await ctx.stub.putState(tallyKey(electionId), Buffer.from(JSON.stringify(tally)));
    }

    return JSON.stringify({ electionId, closedAt, status: 'CERRADA' });
  }

  // ── Private helpers ─────────────────────────────────────────────────────────

  private async _incrementTally(
    ctx: Context,
    electionId: string,
    candidateId: string,
    timestamp: string,
  ): Promise<void> {
    const key = tallyKey(electionId);
    const bytes = await ctx.stub.getState(key);

    let tally: TallyAsset;
    if (!bytes || bytes.length === 0) {
      tally = {
        assetType: 'tally',
        electionId,
        results: { votos_blancos: 0, votos_nulos: 0 },
        lastUpdated: timestamp,
      };
    } else {
      tally = JSON.parse(bytes.toString());
    }

    tally.results[candidateId] = (tally.results[candidateId] ?? 0) + 1;
    tally.lastUpdated = timestamp;

    await ctx.stub.putState(key, Buffer.from(JSON.stringify(tally)));
  }

}
